/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "BackendService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "BackendVpc": {
      "type": "sst.aws.Vpc"
    }
    "BookingQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ExportExcelBookings": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ExportExcelOrders": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "IssueTicketQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "LangfarmTicketBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Nextjs": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}