# name: SST workflow
# on:
#   push:
#     branches:
#       - master

# # Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
# concurrency:
#   group: merge-${{ github.ref }}

# permissions:
#   id-token: write # This is required for requesting the JWT
#   contents: read # This is required for actions/checkout

# jobs:
#   DeployApp:
#     runs-on: ubuntu-latest
#     env:
#       #Define your envs needed for static generation:
#       APP_PORT: ${{ secrets.APP_PORT }}
#       APP_PREFIX: ${{ secrets.APP_PREFIX }}
#       APP_CORS: ${{ secrets.APP_CORS }}
#       NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
#       NEXT_PUBLIC_WEATHER_API_KEY: ${{ secrets.NEXT_PUBLIC_WEATHER_API_KEY }}
#       COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
#       COGNITO_USER_CLIENT_ID: ${{ secrets.COGNITO_USER_CLIENT_ID }}
#       NEXT_PUBLIC_REGION: ${{ secrets.NEXT_PUBLIC_REGION }}
#       NEXT_PUBLIC_LFC_URL: ${{ secrets.NEXT_PUBLIC_LFC_URL }}
#       DB_MONGO_URI: ${{ secrets.DB_MONGO_URI }}
#       BE_URL: ${{ secrets.BE_URL }}
#       SPARK_POST_KEY: ${{ secrets.SPARK_POST_KEY }}
#       SECRET_KEY: ${{ secrets.SECRET_KEY }}
#       FE_URL: ${{ secrets.FE_URL }}
#       FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
#       FROM_EMAIL_NAME: ${{ secrets.FROM_EMAIL_NAME }}
#       NEXT_PUBLIC_DW_API_URL: ${{ secrets.NEXT_PUBLIC_DW_API_URL }}
#       PAYOO_POS_NOTIFY_URL: ${{ secrets.PAYOO_POS_NOTIFY_URL }}
#       COGNITO_REGION: ${{ secrets.COGNITO_REGION }}
#       NEXT_PUBLIC_TICKET_URL: ${{ secrets.NEXT_PUBLIC_TICKET_URL }}
#       LFC_VPC_URL: ${{ secrets.LFC_VPC_URL }}


#     #Define your envs needed for static generation:
#     steps:
#       - name: Git clone the repository
#         uses: actions/checkout@v3
#       - name: Install pnpm
#         uses: pnpm/action-setup@v4
#         with:
#           version: 9
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           role-to-assume: arn:aws:iam::340117293020:role/Github
#           role-duration-seconds: 3600 #adjust as needed for your build time
#           aws-region: ap-southeast-1
#       - name: Deploy app
#         run: |
#           pnpm install && npx sst unlock --stage production && npx sst deploy --stage production
